apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: autoservice
  labels:
    app: backend
type: Opaque
stringData:
  SPRING_DATASOURCE_PASSWORD: "test@1234"
  JWT_SECRET: "mySecretKeyForJWTTokenGenerationThatShouldBeLongEnoughForSecurity"
  SPRING_MAIL_USERNAME: "your-email@gmail.com"
  SPRING_MAIL_PASSWORD: "your-app-password"
