# PersistentVolumeClaim for PostgreSQL data storage
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: autoservice
  labels:
    app: postgres
spec:
  accessModes:
    - ReadWriteOnce  # Can be mounted by a single node
  resources:
    requests:
      storage: 10Gi  # Request 10GB of storage
  storageClassName: standard  # Change based on your cluster's storage class