# Secret for PostgreSQL Database
# Base64 encode password: echo -n 'postgres123' | base64
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: autoservice
  labels:
    app: postgres
type: Opaque
data:
  # postgres123 (base64 encoded)
  POSTGRES_PASSWORD: cG9zdGdyZXMxMjM=